"""
TavilyCorroborator: Executes multiple Tavily searches using the queries
generated by Ollama, collects up to 50 unique results, filters by trusted
domains, and returns a scored CorroborationResult.
"""

import urllib.parse
import logging
from typing import List, Dict, Any, Optional, Set

from tavily import TavilyClient

from src.schemas.article_schema import CorroborationResult, CorroboratingSource
from src.config.settings import settings

logger = logging.getLogger(__name__)

# ── Trusted Domain Lists ──────────────────────────────────────────────────────

TIER_1_DOMAINS: Set[str] = {
    # International wire services — gold standard
    "reuters.com", "apnews.com", "afp.com", "bloomberg.com",
    # Top international broadcasters / newspapers
    "bbc.com", "bbc.co.uk", "theguardian.com", "nytimes.com",
    "washingtonpost.com", "wsj.com", "ft.com", "economist.com",
    # Science / health / government
    "nature.com", "science.org", "who.int", "cdc.gov",
    "nih.gov", "nasa.gov", "pubmed.ncbi.nlm.nih.gov",
    # Fact-checking
    "snopes.com", "factcheck.org", "politifact.com", "fullfact.org",
}

TIER_2_DOMAINS: Set[str] = {
    # Established international outlets
    "theatlantic.com", "npr.org", "pbs.org", "vox.com", "axios.com",
    "abc.net.au", "cbc.ca", "abc.go.com", "nbcnews.com", "cbsnews.com",
    "abcnews.go.com", "usatoday.com", "time.com", "forbes.com",
    "businessinsider.com", "thehill.com", "politico.com",
    # International
    "dw.com", "aljazeera.com", "france24.com", "scmp.com",
    # Academic / research
    "sciencedirect.com", "arxiv.org", "jstor.org", "springer.com",
    # Government / intergovernmental
    "un.org", "europa.eu", "gov.uk", "congress.gov",
}

ALL_TRUSTED = TIER_1_DOMAINS | TIER_2_DOMAINS

# Domains that are known unreliable — hard penalty
KNOWN_UNRELIABLE: Set[str] = {
    "infowars.com", "naturalnews.com", "beforeitsnews.com",
    "worldnewsdailyreport.com", "theonion.com", "clickhole.com",
    "empirenews.net", "huzlers.com", "newslo.com",
}


class TavilyCorroborator:
    """
    Runs up to 5 Tavily search queries (from Ollama's output),
    collects up to 50 unique articles, and scores how well
    trusted outlets corroborate the original article.
    """

    MAX_TOTAL_RESULTS = 50
    MAX_PER_QUERY = 10

    def __init__(self, api_key: Optional[str] = None):
        key = api_key or settings.tavily_api_key
        if not key:
            raise ValueError("TAVILY_API_KEY not set in .env")
        self.client = TavilyClient(api_key=key)

    # ── Main entry point ──────────────────────────────────────────────────

    def corroborate(
        self,
        search_queries: List[str],
        article_title: str,
    ) -> CorroborationResult:
        """
        Run multiple Tavily searches, deduplicate, classify, and score results.
        """
        if not search_queries:
            search_queries = [article_title[:150]]

        # Always include the article title itself as one search
        queries_to_run = list(dict.fromkeys([article_title[:150]] + search_queries))[:5]

        all_results: List[CorroboratingSource] = []
        seen_urls: Set[str] = set()
        queries_used: List[str] = []

        for query in queries_to_run:
            if len(all_results) >= self.MAX_TOTAL_RESULTS:
                break
            results = self._search_one_query(query, seen_urls)
            all_results.extend(results)
            queries_used.append(query)
            for r in results:
                seen_urls.add(r.url)

        # Sort: trusted first, then by relevance score
        all_results.sort(key=lambda r: (-r.tier, -r.relevance_score))
        top_50 = all_results[:self.MAX_TOTAL_RESULTS]

        # Count tiers
        tier1 = [r for r in top_50 if r.tier == 1]
        tier2 = [r for r in top_50 if r.tier == 2]
        trusted = tier1 + tier2

        score = self._compute_score(len(tier1), len(tier2), len(top_50))
        verdict = self._verdict_label(len(tier1), len(tier2))

        return CorroborationResult(
            total_sources_found=len(top_50),
            trusted_sources_count=len(trusted),
            tier1_count=len(tier1),
            tier2_count=len(tier2),
            corroboration_score=score,
            verdict_label=verdict,
            top_sources=top_50,
            search_queries_used=queries_used,
        )

    # ── Search helpers ────────────────────────────────────────────────────

    def _search_one_query(
        self, query: str, seen_urls: Set[str]
    ) -> List[CorroboratingSource]:
        try:
            response = self.client.search(
                query=query,
                search_depth="basic",
                topic="news",
                max_results=self.MAX_PER_QUERY,
                include_answer=False,
                include_raw_content=False,
            )
            results = []
            for r in response.get("results", []):
                url = r.get("url", "")
                if not url or url in seen_urls:
                    continue
                domain = self._domain(url)
                tier = self._classify_tier(domain)
                results.append(CorroboratingSource(
                    url=url,
                    title=r.get("title", ""),
                    domain=domain,
                    snippet=r.get("content", "")[:300],
                    trusted=(tier > 0),
                    tier=tier,
                    search_query=query,
                    relevance_score=float(r.get("score", 0.0)),
                ))
            return results
        except Exception as e:
            logger.error(f"Tavily search failed for query '{query[:60]}': {e}")
            return []

    # ── Scoring ───────────────────────────────────────────────────────────

    def _compute_score(self, tier1: int, tier2: int, total: int) -> float:
        if total == 0:
            return 0.10

        score = 0.15   # base

        # Tier 1 contributions (heavy weight)
        if tier1 >= 5:
            score += 0.65
        elif tier1 >= 3:
            score += 0.55
        elif tier1 >= 2:
            score += 0.42
        elif tier1 == 1:
            score += 0.28

        # Tier 2 contributions (moderate weight)
        if tier2 >= 5:
            score += 0.20
        elif tier2 >= 3:
            score += 0.12
        elif tier2 >= 1:
            score += 0.05

        # Penalty: many results but none trusted
        if tier1 == 0 and tier2 == 0:
            score = max(0.10, score - 0.10)

        return round(min(score, 1.0), 3)

    def _verdict_label(self, tier1: int, tier2: int) -> str:
        if tier1 >= 3:
            return f"Strongly corroborated — {tier1} top-tier outlets (Reuters/BBC-level) covering this story"
        elif tier1 >= 1:
            return f"Corroborated — {tier1} top-tier outlet(s) + {tier2} secondary trusted source(s)"
        elif tier2 >= 3:
            return f"Partially corroborated — {tier2} secondary trusted sources found, but no tier-1 outlets"
        elif tier2 >= 1:
            return f"Weakly corroborated — only {tier2} secondary source(s) found"
        else:
            return "Not corroborated — no trusted news outlet found covering this story"

    # ── Utils ─────────────────────────────────────────────────────────────

    def _classify_tier(self, domain: str) -> int:
        if any(t in domain for t in TIER_1_DOMAINS):
            return 1
        if any(t in domain for t in TIER_2_DOMAINS):
            return 2
        # Generic .gov and .edu get tier 2
        if domain.endswith(".gov") or domain.endswith(".edu"):
            return 2
        return 0

    def _domain(self, url: str) -> str:
        try:
            return urllib.parse.urlparse(url).netloc.lower().replace("www.", "")
        except Exception:
            return url

    def format_results_for_llm(self, corr: CorroborationResult) -> str:
        """Format corroboration results as a readable block for the Ollama reasoning prompt."""
        lines = []
        for i, src in enumerate(corr.top_sources[:20], 1):
            tier_label = f"[TIER {src.tier}]" if src.trusted else "[UNKNOWN]"
            lines.append(
                f"{i}. {tier_label} {src.domain}\n"
                f"   Title: {src.title[:80]}\n"
                f"   Snippet: {src.snippet[:150]}"
            )
        return "\n\n".join(lines) if lines else "No results found."
